### ISSUE TITLE
Does this package support SELECT_TF_OPS 

### ISSUE THREAD

**Issue by bmabir17** [jackwish/tflite#3]
I have [mask-rcnn](https://github.com/matterport/Mask_RCNN/issues/563) model which uses some operators(ResizeNearestNeighbor, Stack, and TensorFlowShape) that are not supported by current tf lite python api found in tensorflow package for inference. The tf lite documentation says that it is under active development [here](https://www.tensorflow.org/lite/guide/ops_select#python_pip_package). So does this package support those tensorflow ops? 

P.S.
I found one [solution](https://medium.com/@bsramasubramanian/running-a-tensorflow-lite-model-in-python-with-custom-ops-9b2b46efd355) on how to build a python package with those ops but i am kinda new to building package from source.

**Comment by zhenhuaw-me** [comment]
Hi @bmabir17 , this package supports `TFLITE_BUILTINS` only currently, as it is generated from the schema defined by TFLite.

Not sure how will TFLite enable `SELECT_TF_OPS`. If by a *Customized Operator* approach, I think we can manully extend this package like the document you found. Otherwise, we can wait to see the detail.
